ver_plugin: joyent
driver_config:
  joyent_username: <%= ENV['SDC_CLI_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_CLI_IDENTITY'] %>
  joyent_keyname: <%= ENV['SDC_CLI_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_CLI_URL'] %>
  joyent_version: '~7.1'
  joyent_ssl_verify_peer: false
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: smartos
    provisioner:
      chef_omnibus_url: 'https://raw.githubusercontent.com/SIGUSR2/kitchen-smartos/master/smartos_chef.sh'
      ruby_bindir: '/opt/local/bin'
    busser:
      ruby_bindir: '/opt/local/bin'
    driver_config:
      joyent_image_id: <joyent smartos image_id>
      joyent_flavor_id: <joyent flavor name>
      joyent_networks:
        - <joyent default network uuid>
  - name: ubuntu14
    busser:
      sudo: true
    driver_config:
      username: ubuntu
      joyent_image_id: <joyent ubuntu image_id>
      joyent_flavor_id: <joyent flavor name>
      joyent_networks:
        - <joyent default network uuid>

suites:
  - name: <suite name>
    run_list:
      - recipe[foo::bar]
